components:
  examples:
    sampleHiBON:
      value: "77+9ARoGQklHSU5U77+977+977+977+977+977+977+977+977+985C1h1kIB0JPT0xFQU4BFwdGTE9BVDMy77+9cO+/vT8YB0ZMT0FUNjTGhe+/vW/ZtXlpEQVJTlQzMlYSBUlOVDY077+977+977+977+977+9fRQGVUlOVDMyKhUGVUlOVDY077+977+977+977+977+9zZgCAglzdWJfaGlib24pAwZCSU5BUlkEAQIDBAEGU1RSSU5HBFRleHQJBFRJTUXvv73vv73vv73oiLjvv73vv70ICg=="
    sampleBase64:
      value: "@RhgHRkxPQVQ2NMaF4m_ZtXlpAglzdWJfaGlib24pAwZCSU5BUlkEAQIDBAEGU1RSSU5HBFRleHQJBFRJTUWfyZuTm7vu7Qg"
    sampleJson:
      value:
        FLOAT64:
          - "f64"
          - "0x1.9b5d96fe285c6p+664"
        sub_hibon:
          BINARY:
            - "*"
            - "@AQIDBA=="
          STRING: "Text"
          TIME:
            - "time"
            - "2023-09-20T13:01:25.5186591"
    sampleValid: 
      value:
        code: 0
        output: ""
    sampleInvalid: 
      value:
        code: 1
        output: "Error: Invalid ISO Extended String: 200116T14:18:10.7747593"
    sampleDARTIndex:
      value:
        dartindex: "@4NFsU9l9xCcwbflc6wZiadg7hSz8LQmAzjnltp-i-Zs="
    version:
      value: |
        git: git@github.com:tagion/tagion.git
        branch: HEAD
        hash: 7339653f5a55046171951f1d69e1a481f81981d5
        revno: 12812
        build_date: 2023-12-04 16:00
        builder_name: Ze bot
        builder_email: gitbot@decard.io
        CC: cc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
        DC: DMD64 D Compiler v2.105.2