---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: dev-hibon-service
spec:
  selector:
    matchLabels:
      app: dev-hibon-service
  replicas: 1
  template:
    metadata:
      labels:
        app: dev-hibon-service
    spec:
      containers:
      - name: dev-hibon-service
        image: 763081292656.dkr.ecr.eu-central-1.amazonaws.com/hibon-service
        ports:
        - containerPort: 3000
        env:
        - name: GITBOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: gitbot-token-secret
              key: token

---
apiVersion: v1
kind: Service
metadata: 
  name: dev-hibon-service
spec:
  type: ClusterIP
  selector:
    app: dev-hibon-service
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
