---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: prod-hibon-service
spec:
  selector:
    matchLabels:
      app: prod-hibon-service
  replicas: 1
  template:
    metadata:
      labels:
        app: prod-hibon-service
    spec:
      containers:
      - name: prod-hibon-service
        image: 763081292656.dkr.ecr.eu-central-1.amazonaws.com/hibon-service
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata: 
  name: prod-hibon-service
spec:
  type: ClusterIP
  selector:
    app: prod-hibon-service
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
