name: Main Flow
on:
  workflow_dispatch:
  push: 
    branches: 
      - master
env:
  GITBOT_TOKEN: ${{ secrets.GITBOT_TOKEN }}
  BIN_DIR: /home/gitbot/actions-runner/_work/npm-hibonutil/npm-hibonutil/artifact/build/x86_64-linux/bin
  WORK_DIR: /home/gitbot/actions-runner/_work/npm-hibonutil/npm-hibonutil/
permissions:
  contents: read
  pages: write
  id-token: write 

jobs:
  deploy:
    runs-on: hibon-ec2
    steps: 
      - name: Checkout
        uses: actions/checkout@v4.1.0
        
      - name: build and run service
        run: |
          export GH_TOKEN=${{ env.GITBOT_TOKEN }}
          rm -rf artifact
          mkdir -p artifact || echo "artifact dir already exists"
          cd artifact && gh run download -n successful_artifact --repo tagion/tagion
          tar -xzf *.tar.gz
          rm -r *.tar.gz
          cd ..
          source ~/.bashrc
          #cd ${{ env.BIN_DIR }}
          cd /home/gitbot/actions-runner/_work/npm-hibonutil/npm-hibonutil/artifact/build/x86_64-linux/bin
          ln -s tagion hibonutil
          chmod +x hibonutil
          #cd ${{ env.WORK_DIR }}
          cd /home/gitbot/actions-runner/_work/npm-hibonutil/npm-hibonutil/
          pkill node || echo "node pid killed"
          npm install
          #npm install eslint pm2
          npm run build
          #nohup npm run start -- --trusted
          sudo service nginx restart
  
