name: Main Flow
on:
  workflow_dispatch:
  push: 
    branches: 
      - master
env:
  TARGET: x86_64-linux
  STAGE: commit
  DC: dmd
  CD_PARALLEL: 2
  RETENTION_DAYS_BINS: 3
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  UNITTEST_COV: unittest-cov
  GITBOT_TOKEN: ${{ secrets.GITBOT_TOKEN }}
permissions:
  contents: read
  pages: write
  id-token: write 

jobs:
  deploy:
    runs-on: hibon-ec2
    steps: 
      - name: Checkout
        uses: actions/checkout@v4.1.0
        
      - name: build and run service
        run: |
          npm install
          npm install eslint
          npm run build
          pm2 restart 0
  
